### ISSUE TITLE
Aggiornare gli shapefile ISTAT al 2019

### ISSUE THREAD

**Issue by jenkin** [teamdigitale/pdnd-open-notebooks#2]
Download diretto (versione generalizzata): http://www.istat.it/storage/cartografia/confini_amministrativi/generalizzati/Limiti01012019_g.zip.

Fonte ISTAT: https://www.istat.it/it/archivio/222527.

cc @alevanno

**Comment by giux78** [comment]
closed by https://github.com/teamdigitale/pdnd-open-notebooks/pull/3
